version: '3'
services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_app
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    container_name: service
    build:
      context: .
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/data/static:ro
    depends_on:
      - backend
    ports:
      - "8000:80"

volumes:
  postgres_volume:
  static_volume:
